version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    restart: on-failure
    command: "yarn start:prod"
